### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by surajkadapa** [acmpesuecc/rock_paper_scissor#1]
The game is not following the conventional rules for some reason, make sure it does.

**Comment by AnshulBanda** [comment]
hey can i get assigned to this?

**Comment by akdino** [comment]
can i get assigned ?

**Comment by akdino** [comment]
can i get assigned

**Comment by surajkadapa** [comment]
@AnshulBanda Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by 825pranav** [comment]
hey can I be assigned to this?

**Comment by komulannister** [comment]
can i get assigned to this?

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by diishanbhag** [comment]
please assign me this.

**Comment by KaashviR** [comment]
Please assign it to me

**Comment by AnshulBanda** [comment]
i need help

**Comment by surajkadapa** [comment]
@AnshulBanda  you are assigned 30 more mins.

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by surajkadapa** [comment]
@AnshulBanda Give update in 20 mins.

**Comment by diishanbhag** [comment]
can i be assigned to this

**Comment by AnshulBanda** [comment]
i seem to be done, you can come and check

**Comment by surajkadapa** [comment]
This issue has been solved.
