### ISSUE TITLE
Add another element in the game

### ISSUE THREAD

**Issue by surajkadapa** [acmpesuecc/rock_paper_scissor#3]
Add another input element to the game other than the given rock, paper, and scissor which follows defined rules(set by you) and make sure the game works with those rules. \
P.S. the output system of one LED doesn't need to be changed.

**Comment by likhitharigela** [comment]
I would like to work on this

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by surajkadapa** [comment]
@likhitharigela Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by Idkwhatnametogive** [comment]
Hey, I'd like to get assigned to this!

**Comment by Lalith2907** [comment]
Can I get assigned to this?

**Comment by AmeyaKhanzode** [comment]
I would like to work on this

**Comment by icantype1912** [comment]
I would like to work on this please

**Comment by ankitam389** [comment]
can i be assigned to this?

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by Ananya-Kini** [comment]
can i pls get assigned

**Comment by rishilg** [comment]
can i get assigned

**Comment by surajkadapa** [comment]
@likhitharigela 20 mins extra

**Comment by surajkadapa** [comment]
@Idkwhatnametogive Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
@AmeyaKhanzode Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by SnehaBangera** [comment]
can i get assigned to #3

**Comment by kabir325** [comment]
i want it now

**Comment by surajkadapa** [comment]
@AmeyaKhanzode i am reassigning it because time is out.

**Comment by surajkadapa** [comment]
@Arty1912 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
@kabir325 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by Hiyanachnani** [comment]
hiii i would like to work on this please assign it to me

**Comment by itsA-D** [comment]
can i get assign to it

**Comment by Lalith2907** [comment]
can i get assigned to it?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by itsA-D** [comment]
assign plz

**Comment by surajkadapa** [comment]
The issue has been solved.
